language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 5.6

before_script:
  - composer update --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php ./vendor/bin/coveralls -v
